services:
  yshop-app:
    build: .
    image: "yshop"
    container_name: "yshop-app"
    entrypoint: ["uvicorn", "--host=0.0.0.0", "main:app", "--reload"]
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/src

  postgres:
    image: postgres
    container_name: "yshop-postgres"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
